#! /usr/bin/python

# ***********************************************************************
# Copyright (c) 2017 Unity Technologies. All rights reserved.
#
# Licensed under the ##LICENSENAME##.
# See LICENSE.md file in the project root for full license information.
# ***********************************************************************

import re
import sys
import time

# Input:
# 1- full path to the output .i file
# 2- full path to the fbx header file to read (fbxdatatypes.h)
# Output:
# - a swig .i file to be %included at the end of the fbxdatatypes.i file,
#   to include all the constants

output_filename = sys.argv[1]
header_path = sys.argv[2]

with open(header_path) as infile:
  with open(output_filename, 'w') as outfile:
    outfile.write("/* Automatically generated by {} at {} */\n\n".format(
        sys.argv[0], time.ctime()));
    for line in infile:
      m = re.search(r'extern FBXSDK_DLL FbxDataType ([a-zA-Z0-9_]+);', line)
      if m:
        outfile.write("%fbxdatatype({});\n".format(m.group(1)))

